print(' ')
print('\033[7;33m                                         \033[m')
print('\033[7;33m          CALCULADORA  CASHBACK          \033[m')
print('\033[7;33m                                         \033[m')
print(' ')
menu = 0
while menu != 3:
    print('=' * 41)
    print('''    [1] Calcular Cashback
    [2] Simular Preço com Resgate
    [3] Encerrar Programa''')
    print('=' * 41)
    print(' ')
    menu = int(input('Escolha uma das opções: '))
    nome = ''
    if menu == 1:
        nome = str(input('Nome do passageiro: '))
        num = 1
        cont = acum1 = acum11 = 0
        while num != 0:
            num = float(input('Digite o valor da viagem R$: '))
            cont += 1
            acum1 = acum1 + (num * 0.02)
            acum11 = (acum11 + acum1) * 0.85
            if num == 0:
                cont -= 1
            fim = str(input('Deseja continuar com o registro? [S/N]')).upper().strip()
            if fim == 'S':
                num = 1
            elif fim == 'N':
                num = 0
        print(' ')
        print('=' * 41)
        print(' ')
        print(' ')
        print('\033[7;33m                                         \033[m')
        print('\033[7;33m            CASHBACK A RESGATAR          \033[m')
        print('\033[7;33m                                         \033[m')
        print(' ')
        print(' ')
        print('Registrada(s) \033[33m{}\033[m viagem(ns) em nome de'.format(cont))
        print('\033[33m{}\033[m'.format(nome))
        print(' ')
        print(' 》 Desconto Viagem Curta é de \033[7;33mR${:.2f}\033[m 《'.format(acum1))
        print(' ')
        print('                  \033[7;33mOU\033[m                 ')
        print(' ')
        print(' 》 Desconto Viagem Longa é de \033[7;33mR${:.2f}\033[m 《'.format(acum11))
        print(' ')
        print(' ')
        print(' ')
        print('*' * 41)
        print('     App developed by BRUNO GIANETTI')
        print('*' * 41)
        print(' ')
        print(' ')
        print('social media:')
        print(' ')
        print('whatsapp: (19) 98192-2647')
        print('instagran: @ubertraderitaliano')
        print('twitter: @bruno_gianetti')
        print('facebook: Bruno Gianetti')
        print('linkedin: Bruno Gianetti')
        print(' ')
        print('Copyright 2019 - v1.0')
        print(' ')
        print(' ')
    if menu == 2:
        print(' ')
        print(' ')
        print('\033[7;33m                                         \033[m')
        print('\033[7;33m           SIMULANDO  CASHBACK           \033[m')
        print('\033[7;33m                                         \033[m')
        print(' ')
        print(' ')
        print(' ')
        valor = float(input('Qual o valor da viagem? '))
        print(' ')
        desc = float(input('Qual o valor do cashback? '))
        print(' ')
        if desc > valor:
            print('Você ganhou uma viagem \033[7;33mGRATUITA\033[m')
        else:
            print('O valor da corrida será de \033[7;33mR${:.2f}\033[m'.format(valor - desc))
        print(' ')
        print(' ')
        print(' ')
        print('*' * 41)
        print('     App developed by BRUNO GIANETTI')
        print('*' * 41)
        print(' ')
        print(' ')
        print('social media:')
        print(' ')
        print('whatsapp: (19) 98192-2647')
        print('instagran: @ubertraderitaliano')
        print('twitter: @bruno_gianetti')
        print('facebook: Bruno Gianetti')
        print('linkedin: Bruno Gianetti')
        print(' ')
        print('Copyright 2019 - v1.0')
        print(' ')
        print(' ')
    if menu == 3:
        print(' ')
        print('\033[7;33m                                         \033[m')
        print('\033[7;33m          CALCULADORA  CASHBACK          \033[m')
        print('\033[7;33m                                         \033[m')
        print(' ')
        print(' ')
        print('》 Não deixe de aproveitar seu bônus ')
        print('  acumulando descontos!')
        print(' ')
        print('》 Peça para simular seu valor de resgate')
        print('  via msg de whatsapp!')
        print(' ')
        print('》 Guarde sempre seus recibos no seu ')
        print('  smartphone!')
        print(' ')
        print('》 Quanto mais você rodar, mais vai ')
        print('  acumular!')
        print(' ')
        print(' ')
        print('*'*41)
        print('     App developed by BRUNO GIANETTI')
        print('*'*41)
        print(' ')
        print(' ')
        print('social media:')
        print(' ')
        print('whatsapp: (19) 98192-2647')
        print('instagran: @ubertraderitaliano')
        print('twitter: @bruno_gianetti')
        print('facebook: Bruno Gianetti')
        print('linkedin: Bruno Gianetti')
        print(' ')
        print('Copyright 2019 - v1.0')